language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py install
  - pip install coveralls

script:
  - coverage run --source=simple_pagination  test_runner.py test

after_success:
  coveralls
